# Generated by Django 5.1.2 on 2025-12-22 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cbv', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentdetails',
            name='currency',
            field=models.CharField(default='INR', max_length=50),
        ),
    ]
